### ISSUE TITLE
Exception has been thrown by the target of an invocation. 417 Critical Exception

### ISSUE THREAD

**Issue by Afondevi** [backand/angular1-sdk#3]
Hi, 

Sometime in my request, I receive this error

```
error:{"error":"Exception has been thrown by the target of an invocation."}
	at (friendShips/pushNewFriendRequest:101)
```

Do you know how can I have more informations on this error ? because in `pushNewFriendRequest` line 101, I send only a request in backand backend.

This probleme reproduce when socket Disconnect and reconnect. When reconnecting, nothing work in my app. a lot of request pass with 417 status.

![capture d ecran 2017-09-24 a 15 54 16](https://user-images.githubusercontent.com/11740298/30783297-de0d731c-a140-11e7-8639-4d891fd95dd5.png)

![capture d ecran 2017-09-24 a 15 54 38](https://user-images.githubusercontent.com/11740298/30783298-e14ac48a-a140-11e7-9217-be7bf81bda4a.png)

Thx, Alex

**Comment by Afondevi** [comment]
Another exemple : 

![capture d ecran 2017-09-24 a 17 11 13](https://user-images.githubusercontent.com/11740298/30783916-6fe69bec-a14b-11e7-8ad1-468bc770212b.png)

**Comment by rannn505** [comment]
Fixed in last commit
